import type { Project } from "../types/Project";
const imagesDir = "/images/";

//<span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold "></span>,
export const PROJECTS: Project[] = [
  {
    name: "Financial AI Companion",
    image: imagesDir + "financial_ai_companion.webp",
    description: `This project was created during a Hackathon (<span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">HackUPC</span>) that I participated in with a friend. We had 36 hours to develop and demo the idea. We built a <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">financial companion</span> app that helps users with their investments and <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">planning</span>. The app is <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">AI-powered</span> and uses <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">Llama</span> to provide advice through a microservice built with <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">Node.js</span> and Express. We used <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">Go</span> as the main backend language, and the frontend was developed with <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">React.js</span> and <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">Tailwind CSS</span>.`,
    repositoryLink: "https://github.com/arcedo/financial-ai-backend",
    pageLink: "https://devpost.com/software/financial-ai-companion",
    tecnologies: [
      "Llama",
      "Go",
      "TypeScript",
      "React.js",
      "MongoDB",
      "Tailwind CSS",
    ],
    date: "2 - 4 May 2025",
  },
  {
    name: "Apex",
    image: imagesDir + "apex.webp",
    description: `Landing page for Apex team, a company related to fundraising. It contains <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">information</span> about the team and an <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">application form</span>. The page is <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">responsive</span> and <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">SEO optimized</span>.`,
    repositoryLink: "https://we-apex.com",
    tecnologies: ["TypeScript", "Tailwind CSS", "Astro.js", "Svelte"],
    date: "Nov 2024 - Present",
  },
  {
    name: "fundflow",
    image: imagesDir + "fundflow.webp",
    description: `A <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">crowdfunding platform</span> with <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold">social media features</span> like follows, likes/dislikes, and reviews from collaborators and funders. This was a <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">final grade project</span> done in pairs, with a <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">three-month timeframe</span> to brainstorm, design, and develop the app. We created <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">use case diagrams</span>, <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">designed</span> the <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">UI</span>/<span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">UX</span>, and <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">structured the database</span>. Finally, we developed the app with our chosen tech stack and <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">presented</span> the results <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">to a committee</span>.`,
    pageLink: "https://fundflow.arcedo.dev/home",
    repositoryLink: "https://github.com/arcedo/fundflow-Backend",
    tecnologies: [
      "JavaScript",
      "bun.JS",
      "express",
      "JWT",
      "Resend",
      "MySQL",
      "MongoDB",
      "Docker",
      "Nginx",
      "React.js",
      "Tailwind CSS",
      "Google OAuth",
    ],
    date: "Feb - May 2024",
  },
  {
    name: "Cargo Loading",
    image: imagesDir + "cargo_loading.webp",
    description: `<span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">Web service</span> that determines whether multiple <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">elements</span> can <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">fit within a container</span>, and if so, <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">identifies the optimal arrangement and order</span>. This <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">open-source project</span> is from <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">CodeBiting</span>, where I completed an <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">internship</span> and <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">contributed</span> to the <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">development</span> of the <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">REST API</span> and a <span class="group-hover:text-accent/90 transition-colors duration-500 font-semibold ">demo frontend</span> page.`,
    repositoryLink: "https://github.com/CodeBiting/onion-cargo-loading-service",
    tecnologies: [
      "JavaScript",
      "Node.js",
      "Express",
      "Mocha",
      "Swagger",
      "Pug.js",
    ],
    date: "Jul - Dec 2023",
  },
];
